version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/mini_project5
    overwrite: true

permissions:
  - object: /home/ubuntu/mini_project5/scripts/deploy.sh
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: 755

hooks:
  ApplicationStart:
    - location: scripts/deploy.sh
      timeout: 300
      runas: ubuntu
