version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
      nodejs: 20
    commands:
      - echo "Install phase..."
      - chmod +x ./gradlew # 루트에 있으므로 바로 실행 가능
  pre_build:
    commands:
      - export IMAGE_TAG=$(date +%Y%m%d%H%M%S)
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo "Building Backend..."
      - ./gradlew build -x test # 루트에서 백엔드 빌드 실행
      
      # [백엔드 도커 빌드] Dockerfile이 루트에 있으므로 마침표(.) 하나면 끝납니다.
      - echo "Building the backend Docker image..."
      - docker build -t $IMAGE_REPO_NAME_BACKEND:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME_BACKEND:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME_BACKEND:$IMAGE_TAG

  post_build:
    commands:
      - echo "Pushing Images..."
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME_BACKEND:$IMAGE_TAG
      
      # [프론트엔드 도커 빌드] 프론트엔드 폴더로 이동해서 처리
      - cd frontend
      - docker build -t $IMAGE_REPO_NAME_FRONTEND:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME_FRONTEND:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME_FRONTEND:$IMAGE_TAG
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME_FRONTEND:$IMAGE_TAG

artifacts:
  files:
    - '**/*'
  base-directory: 'build/libs' #